project:
  type: website
  output-dir: docs

website:
  title: "datathon_2024"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - nhanes.qmd
      - co2.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



